# Generated by Django 2.1.5 on 2019-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default='입력없음', max_length=20)),
                ('contry', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('review', models.TextField(default='입력없음', max_length=250)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('writer', models.CharField(max_length=20)),
            ],
        ),
    ]
