# Generated by Django 2.1.5 on 2019-05-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20190503_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='writer',
            field=models.CharField(default='gyuzizi', max_length=20),
        ),
    ]
