# Generated by Django 2.1.5 on 2019-03-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_auto_20190307_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='review',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=20),
        ),
    ]
